language: java
jdk: oraclejdk8

# the below travis configuration is needed in order to get oraclejdk8 running
# If not specifying the distribution, travis will through the following error:
#     Expected feature release number in range of 9 to 17, but got: 8
# A google show up the solution for and origin of the issue: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/8

dist: trusty

before_install:
  - ./gradlew clean jar


script:
  - echo "Not running ./gradlew test in favor to the following check test"

stages:
  - check

jobs:
  include:
    - stage: "check"
      name: "$COMPONENT check"
      install: skip
      script:
        - COVERAGE=$NEEDED_COV ./gradlew -p ./monolithic/$COMPONENT check
      env:
        - NEEDED_COV=1.0
        - COMPONENT="ui"

    - stage: "check"
      name: "$COMPONENT $ITEM check"
      install: skip
      script:
        - COVERAGE=$NEEDED_COV ./gradlew -p ./monolithic/$COMPONENT/$ITEM check
      env:
        - NEEDED_COV=1.0
        - COMPONENT="service"
        - ITEM="cart"

    - stage: "check"
      name: "$COMPONENT $ITEM check"
      install: skip
      script:
        - COVERAGE=$NEEDED_COV ./gradlew -p ./monolithic/$COMPONENT/$ITEM check
      env:
        - NEEDED_COV=1.0
        - COMPONENT="service"
        - ITEM="user"

    - stage: "check"
      name: "$COMPONENT $ITEM check"
      install: skip
      script:
        - COVERAGE=$NEEDED_COV ./gradlew -p ./monolithic/$COMPONENT/$ITEM check
      env:
        - NEEDED_COV=1.0
        - COMPONENT="repository"
        - ITEM="order"

    - stage: "check"
      name: "$COMPONENT $ITEM check"
      install: skip
      script:
        - COVERAGE=$NEEDED_COV ./gradlew -p ./monolithic/$COMPONENT/$ITEM check
      env:
        - NEEDED_COV=1.0
        - COMPONENT="repository"
        - ITEM="cart"

    - stage: "check"
      name: "$COMPONENT $ITEM check"
      install: skip
      script:
        - COVERAGE=$NEEDED_COV ./gradlew -p ./monolithic/$COMPONENT/$ITEM check
      env:
        - NEEDED_COV=1.0
        - COMPONENT="repository"
        - ITEM="product"

    - stage: "check"
      name: "$COMPONENT $ITEM check"
      install: skip
      script:
        - COVERAGE=$NEEDED_COV ./gradlew -p ./monolithic/$COMPONENT/$ITEM check
      env:
        - NEEDED_COV=1.0
        - COMPONENT="repository"
        - ITEM="user"

# Generates the test coverage report regarless of the test result (failed or succeeded)
after_script:
  - find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$5}'


deploy:
  provider: script
  script: echo 'WIP'
